name: Build Episode

on: 
  repository_dispatch:
    types: [publish]
  
jobs:
  Publish:
  runs-on: ubuntu-latest
  steps:
    - uses: peter-evans/repository-dispatch@v2
      with:
        issue_number : ${{ github.event.client_payload.issue_number}}
    - run: echo "Hello"$issue_number