name: Build Episode

on:
  issues:
    types: [closed]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'publish')
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{secrets.REPO_ACCESS_TOKEN}}
          event-type: publish
          repository: python-community-news/site
          client_payload: '{"issue_number": "${{ github.event.client_payload.issue_number}}"}'
